In [15]:
import pandas as pd
import numpy as np

lista_de_votacoes = []

name= 'Felipe'

Caipirinha_1 = np.random.random()
Caipirinha_2 = np.random.random()
Caipirinha_3 = np.random.random()
Caipirinha_4 = np.random.random()

Livre_1 = np.random.random()
Livre_2 = np.random.random()
Livre_3 = np.random.random()
Livre_4 = np.random.random()

LeiteCond_1 = np.random.random()
LeiteCond_2 = np.random.random()
LeiteCond_3 = np.random.random()
LeiteCond_4 = np.random.random()

votacao = {
        'Nome': [name,name, name, name],
                'caipirinha': [f'{Caipirinha_1}', f'{Caipirinha_2}', f'{Caipirinha_3}', f'{Caipirinha_4}'],
                'livre': [f'{Livre_1}', f'{Livre_2}', f'{Livre_3}', f'{Livre_4}'],
                'LeiteCond': [f'{LeiteCond_1}', f'{LeiteCond_2}', f'{LeiteCond_3}', f'{LeiteCond_4}']
            }

lista_de_votacoes.append(votacao)
pd.DataFrame(lista_de_votacoes)

,Nome,caipirinha,livre,LeiteCond
0,"[Felipe, Felipe, Felipe, Felipe]","[0.9482572073976521, 0.6690680647368251, 0.167...","[0.7034129903790126, 0.15764987349620496, 0.33...","[0.7340509338767709, 0.5187440990476448, 0.820..."

In [16]:
name= 'Bianca'

Caipirinha_1 = np.random.random()
Caipirinha_2 = np.random.random()
Caipirinha_3 = np.random.random()
Caipirinha_4 = np.random.random()

Livre_1 = np.random.random()
Livre_2 = np.random.random()
Livre_3 = np.random.random()
Livre_4 = np.random.random()

LeiteCond_1 = np.random.random()
LeiteCond_2 = np.random.random()
LeiteCond_3 = np.random.random()
LeiteCond_4 = np.random.random()

votacao = {
        'Nome': [name,name, name, name],
                'caipirinha': [f'{Caipirinha_1}', f'{Caipirinha_2}', f'{Caipirinha_3}', f'{Caipirinha_4}'],
                'livre': [f'{Livre_1}', f'{Livre_2}', f'{Livre_3}', f'{Livre_4}'],
                'LeiteCond': [f'{LeiteCond_1}', f'{LeiteCond_2}', f'{LeiteCond_3}', f'{LeiteCond_4}']
            }

lista_de_votacoes.append(votacao)
pd.DataFrame(lista_de_votacoes)

,Nome,caipirinha,livre,LeiteCond
0,"[Felipe, Felipe, Felipe, Felipe]","[0.9482572073976521, 0.6690680647368251, 0.167...","[0.7034129903790126, 0.15764987349620496, 0.33...","[0.7340509338767709, 0.5187440990476448, 0.820..."
1,"[Bianca, Bianca, Bianca, Bianca]","[0.1119410913525869, 0.805262259492667, 0.4440...","[0.415695776817554, 0.30887053234962936, 0.022...","[0.43395671192966123, 0.19202200569224526, 0.9..."

In [1]:
import pandas as pd
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']

creds = ServiceAccountCredentials.from_json_keyfile_name('copo-do-mundo-405823-5b80939d0ba1.json', scope)
client = gspread.authorize(creds)

sheet = client.open_by_url('https://docs.google.com/spreadsheets/d/1QBd7oQLc5pRRjJZVSleTEhiRYN0K0JLjf8HyO0xBzIE/edit#gid=503153671')

sheet.worksheet('copo_do_mundo').append_row(['value_1','value_2','value_3','value_4','value_5','value_6'])

{'spreadsheetId': '1QBd7oQLc5pRRjJZVSleTEhiRYN0K0JLjf8HyO0xBzIE',
 'tableRange': 'copo_do_mundo!A1:F109',
 'updates': {'spreadsheetId': '1QBd7oQLc5pRRjJZVSleTEhiRYN0K0JLjf8HyO0xBzIE',
  'updatedRange': 'copo_do_mundo!A110:F110',
  'updatedRows': 1,
  'updatedColumns': 6,
  'updatedCells': 6}}

In [ ]:
import pandas as pd
import gspread
from oauth2client.service_account import ServiceAccountCredentials

scope = ['https://spreadsheets.google.com/feeds', 'https://www.googleapis.com/auth/drive']

creds = ServiceAccountCredentials.from_json_keyfile_name('nome_do_seu_arquivo.json', scope)
client = gspread.authorize(creds)

sheet = client.open_by_url('https://docs.google.com/spreadsheets/d/link_da_sua_planilha')

sheet.worksheet('nome_da_aba_da_planilha').append_row(['value_1','value_2','value_3','value_4','value_5','value_6'])

In [3]:
df = pd.DataFrame(sheet.worksheet('copo_do_mundo').get_all_records())

In [12]:
df_sum = df.drop(columns=['Nome']).groupby(['Categoria', 'Drink']).sum().reset_index()

import seaborn as sns
import pandas as pd
cm = sns.color_palette("blend:white,green", as_cmap=True)

df_sum.style.background_gradient(cmap = cm,axis=None)